In [1]:
import pandas as pd    # tables and data manipulation
import numpy as np     # math and numbers
import os              # file and folder navigation

In [2]:
print("Current folder:", os.getcwd())
print("All files here:", os.listdir())

Current folder: c:\Users\imagatsya\Downloads\credit-risk-model-main
All files here: ['.gitignore', '01_data_loading.ipynb', '02_data_cleaning.ipynb', '03_eda_visualization.ipynb', '04_feature_engineering.ipynb', '05_model_building.ipynb', 'app.py', 'Data', 'outputs', 'README.md']

In [3]:
print("Current working directory:", os.getcwd())
print("Files in current folder:", os.listdir())

Current working directory: c:\Users\imagatsya\Downloads\credit-risk-model-main
Files in current folder: ['.gitignore', '01_data_loading.ipynb', '02_data_cleaning.ipynb', '03_eda_visualization.ipynb', '04_feature_engineering.ipynb', '05_model_building.ipynb', 'app.py', 'Data', 'outputs', 'README.md']

In [6]:
os.chdir(r"C:\Users\imagatsya\Downloads\credit-risk\credit-risk-model")

print("FIXED WORKING DIR:", os.getcwd())

FIXED WORKING DIR: C:\Users\imagatsya\Downloads\credit-risk\credit-risk-model

In [7]:
print(os.listdir())
print(os.listdir("data"))

['.git', '.ipynb_checkpoints', 'data', 'outputs', 'src']
[]

In [8]:
import os

path = "Data/accepted_2007_to_2018Q4.csv"
print("Size:", round(os.path.getsize(path) / 1e9, 2), "GB")

with open(path, "rb") as f:
    print(f.read(60))

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Data/accepted_2007_to_2018Q4.csv'

In [9]:
print("CURRENT FOLDER:", os.getcwd())
print("FILES HERE:", os.listdir())

CURRENT FOLDER: C:\Users\imagatsya\Downloads\credit-risk\credit-risk-model
FILES HERE: ['.git', '.ipynb_checkpoints', 'data', 'outputs', 'src']

In [10]:
print(os.listdir("data"))

[]

In [11]:
print(os.listdir("data"))

[]

In [12]:

columns_we_need = [

    'annual_inc',             
    'emp_length',              
    'home_ownership',          
    'verification_status',    

    # --- LOAN CHARACTERISTICS ---
    # What are the terms of this loan?
    'loan_amnt',               
    'term',                   
    'int_rate',               
    'installment',             
    'grade',                   
    'purpose',                

    # --- CREDIT HISTORY ---
    # What has this person done in the past?
    'fico_range_low',          
    'dti',                     # debt to income — already stretched thin?
    'delinq_2yrs',             
    'mths_since_last_delinq',  # how long ago — recent = still risky
    'pub_rec',                 # bankruptcies — major red flag
    'revol_util',              
    'open_acc',               
    'total_acc',               # length of credit history
    'revol_bal',               # outstanding revolving debt
    'addr_state',              # state economy affects default rates

    # --- TARGET VARIABLE ---
  
    'loan_status',             
]

print(f"We are loading {len(columns_we_need)} columns")
print("Columns:", columns_we_need)

We are loading 21 columns
Columns: ['annual_inc', 'emp_length', 'home_ownership', 'verification_status', 'loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'purpose', 'fico_range_low', 'dti', 'delinq_2yrs', 'mths_since_last_delinq', 'pub_rec', 'revol_util', 'open_acc', 'total_acc', 'revol_bal', 'addr_state', 'loan_status']

In [13]:
print("Loading data in chunks... please wait")
chunks = []

chunk_number = 0

for chunk in pd.read_csv(
    'data/accepted_2007_to_2018Q4.csv',
    usecols=columns_we_need,
    chunksize=50000,
    low_memory=False,
    on_bad_lines='skip'
):
    chunks.append(chunk)
    chunk_number += 1
    print(f"  Loaded chunk {chunk_number} — {chunk_number * 50000:,} rows so far...")

df = pd.concat(chunks, ignore_index=True)
del chunks

print("\n✓ Done!")
print(f"Rows   : {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

Loading data in chunks... please wait

FileNotFoundError: [Errno 2] No such file or directory: 'data/accepted_2007_to_2018Q4.csv'

In [20]:
# See first 5 rows
print("=== FIRST 5 ROWS ===")
display(df.head())

# See data types of each column
print("\n=== COLUMN DATA TYPES ===")
print(df.dtypes)

# See basic statistics for numeric columns
print("\n=== BASIC STATISTICS ===")
display(df.describe())

=== FIRST 5 ROWS ===

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,verification_status,loan_status,...,addr_state,dti,delinq_2yrs,fico_range_low,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc
0,3600.0,36 months,13.99,123.03,C,10+ years,MORTGAGE,55000.0,Not Verified,Fully Paid,...,PA,5.91,0.0,675.0,30.0,7.0,0.0,2765.0,29.7,13.0
1,24700.0,36 months,11.99,820.28,C,10+ years,MORTGAGE,65000.0,Not Verified,Fully Paid,...,SD,16.06,1.0,715.0,6.0,22.0,0.0,21470.0,19.2,38.0
2,20000.0,60 months,10.78,432.66,B,10+ years,MORTGAGE,63000.0,Not Verified,Fully Paid,...,IL,10.78,0.0,695.0,NaN,6.0,0.0,7869.0,56.2,18.0
3,35000.0,60 months,14.85,829.90,C,10+ years,MORTGAGE,110000.0,Source Verified,Current,...,NJ,17.06,0.0,785.0,NaN,13.0,0.0,7802.0,11.6,17.0
4,10400.0,60 months,22.45,289.91,F,3 years,MORTGAGE,104433.0,Source Verified,Fully Paid,...,PA,25.37,1.0,695.0,12.0,12.0,0.0,21929.0,64.5,35.0

=== COLUMN DATA TYPES ===
loan_amnt                 float64
term                       object
int_rate                  float64
installment               float64
grade                      object
emp_length                 object
home_ownership             object
annual_inc                float64
verification_status        object
loan_status                object
purpose                    object
addr_state                 object
dti                       float64
delinq_2yrs               float64
fico_range_low            float64
mths_since_last_delinq    float64
open_acc                  float64
pub_rec                   float64
revol_bal                 float64
revol_util                float64
total_acc                 float64
dtype: object

=== BASIC STATISTICS ===

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,mths_since_last_delinq,open_acc,pub_rec,revol_bal,revol_util,total_acc
count,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260639e+06,2.260668e+06,1.102166e+06,2.260639e+06,2.260639e+06,2.260668e+06,2.258866e+06,2.260639e+06
mean,1.504693e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,3.068792e-01,6.985882e+02,3.454092e+01,1.161240e+01,1.975278e-01,1.665846e+04,5.033770e+01,2.416255e+01
std,9.190245e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,8.672303e-01,3.301038e+01,2.190047e+01,5.640861e+00,5.705150e-01,2.294831e+04,2.471307e+01,1.198753e+01
min,5.000000e+02,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,0.000000e+00,6.750000e+02,1.600000e+01,8.000000e+00,0.000000e+00,5.950000e+03,3.150000e+01,1.500000e+01
50%,1.290000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,3.100000e+01,1.100000e+01,0.000000e+00,1.132400e+04,5.030000e+01,2.200000e+01
75%,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,0.000000e+00,7.150000e+02,5.000000e+01,1.400000e+01,0.000000e+00,2.024600e+04,6.940000e+01,3.100000e+01
max,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,2.260000e+02,1.010000e+02,8.600000e+01,2.904836e+06,8.923000e+02,1.760000e+02